In [52]:
# Load the autoreload extension
%load_ext autoreload

# Autoreload reloads modules before executing code
# 0: disable
# 1: reload modules imported with %aimport
# 2: reload all modules, except those excluded by %aimport
%autoreload 2

import os, sys
sys.path.append('..\\src')

import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [53]:
import rapid_models.doe as doe

In [54]:
doe.fullfact_with_bounds([0.1,0.1,0.1], [0.9,0.9,1.2], [3,3,2])

array([[0.1, 0.1, 0.1],
       [0.5, 0.1, 0.1],
       [0.9, 0.1, 0.1],
       [0.1, 0.5, 0.1],
       [0.5, 0.5, 0.1],
       [0.9, 0.5, 0.1],
       [0.1, 0.9, 0.1],
       [0.5, 0.9, 0.1],
       [0.9, 0.9, 0.1],
       [0.1, 0.1, 1.2],
       [0.5, 0.1, 1.2],
       [0.9, 0.1, 1.2],
       [0.1, 0.5, 1.2],
       [0.5, 0.5, 1.2],
       [0.9, 0.5, 1.2],
       [0.1, 0.9, 1.2],
       [0.5, 0.9, 1.2],
       [0.9, 0.9, 1.2]])

In [55]:
doe.lhs_with_bounds(2,15,[0.1,0.1],[0.9,0.9],42)

array([[0.87826211, 0.64077301],
       [0.66596549, 0.55465368],
       [0.48303066, 0.84914402],
       [0.76432373, 0.59553222],
       [0.60303707, 0.82075917],
       [0.36776451, 0.78187605],
       [0.70224771, 0.15070476],
       [0.11997547, 0.41839519],
       [0.26309779, 0.21498637],
       [0.19237301, 0.48311491],
       [0.8039826 , 0.43132475],
       [0.54289292, 0.70620596],
       [0.3453928 , 0.30619606],
       [0.46439694, 0.18526179],
       [0.21498766, 0.3510972 ]])

In [56]:
import rapid_models.doe.adaptive_learning as doe_al

In [79]:
a=[[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3],[4,4,4,4,4],[5,5,5,5,5]]
b=[[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3],[4,4,4,4,4],[5,5,5,5,5]]
doe_al.dotdot_a_b_aT(a,b), doe_al.dotdot_a_b_aT_for_row_in_a(a,b)

(array([[  75,  150,  225,  300,  375],
        [ 150,  300,  450,  600,  750],
        [ 225,  450,  675,  900, 1125],
        [ 300,  600,  900, 1200, 1500],
        [ 375,  750, 1125, 1500, 1875]]),
 array([  75,  300,  675, 1200, 1875]))

In [67]:
np.random.random((5,5))

array([[0.46801072, 0.63612499, 0.650138  , 0.55902029, 0.42190429],
       [0.59139145, 0.46608505, 0.61187578, 0.20994744, 0.83283306],
       [0.09525889, 0.63521055, 0.28400509, 0.66720956, 0.16712869],
       [0.03719893, 0.24647395, 0.4142921 , 0.50168728, 0.73524437],
       [0.91184504, 0.41756648, 0.39882623, 0.92629532, 0.2814989 ]])

LB.shape

In [43]:
LB

array('string', dtype='<U6')